オーディオリソース対象にmp4形式を含める
akashic-games/akashic-cli-stat pull request #1
Opened 2017-01-30 06:59 UTC by kamakiri01

### このpull requestが解決する内容

コンテンツのサイズ計算に、mp4形式のオーディオファイルを含めます。

### 破壊的変更
なし。

2017-01-30 08:23 UTC, xnv commented on src/stat.ts
> +		largestFileType === FileType.Mp4 ? sizeResult.totalSizeMp4() : sizeResult.totalSizeAac();
これもう上の分岐の中で計算すればよいのではありませんか。
https://github.com/akashic-games/akashic-cli-stat/pull/1/files#diff-6468ec3511c91290ffa5ecfb9baa2181R77

2017-01-30 08:55 UTC, xnv commented on spec/statSpec.js
> +		"[ ] TOTAL SIZE (using mp4): 6.29KB (6443B)\n" +
どうせなので mp4 が最大になるパスもテストしませんか。

2017-01-30 08:57 UTC, xnv commented on src/stat.ts
> +		if (largestFileType === FileType.Aac) param.logger.print("[deprecated] AAC is deprecated. Use MP4 instead.");
「オーディオファイルのうち、ファイルサイズ最大のものが AAC だった時」に警告されるように見えますが、この条件は意図したものでしょうか。 「AAC が存在すること」であれば、 `sizeResult.mp4AudioSize > 0` で間接的にチェックできると思います。

2017-01-30 13:46 UTC, kamakiri01 commented on src/stat.ts
> +		largestFileType === FileType.Mp4 ? sizeResult.totalSizeMp4() : sizeResult.totalSizeAac();
統合できる箇所なのでまとめます。

2017-01-30 13:47 UTC, kamakiri01 commented on spec/statSpec.js
> +		"[ ] TOTAL SIZE (using mp4): 6.29KB (6443B)\n" +
追加します。

2017-01-30 13:47 UTC, kamakiri01 commented on src/stat.ts
> +		if (largestFileType === FileType.Aac) param.logger.print("[deprecated] AAC is deprecated. Use MP4 instead.");
`sizeResult.aacAudioSize` で事実上アセットとして機能するAACファイルを検査できるので、これを使ってチェックします。

2017-01-31 07:33 UTC, lambdataro reviewed
コメントのみです。

2017-01-31 07:33 UTC, lambdataro commented on src/stat.ts
> +				param.logger.print(formatSize("aac audio", sizeResult.aacAudioSize));
個人的にはここに `break;` 入れたいです。

2017-01-31 12:56 UTC, kamakiri01 commented on src/stat.ts
> +				param.logger.print(formatSize("aac audio", sizeResult.aacAudioSize));
akashic-game以下のコードでも `break;` 有無は混在していて厳密には悩ましいところですが、case文にはbreakを持たせる方針で揃えようと思います。

2017-02-01 03:37 UTC, lambdataro approved these changes
:+1:

2017-02-01 03:57 UTC, xnv commented on src/stat.ts
> +						() => {if (!param.raw) param.logger.warn(asset + ".aac, No such file."); })
aac がないことは今後正常系になるので、この警告は不要だと思います。(正しく .ogg と .mp4 を用意しているのに、なぜか warn される、というのは意図した状況ではないように思います)　この警告を削除するだけだと他との対称性がない意味が読み取りにくいので、コメントがあるといいかもしれません。(AAC は対応するが deprecated なのでなくても警告しない、というような内容で)

2017-02-01 03:58 UTC, xnv commented on src/stat.ts
> +						() => {if (!param.raw) param.logger.warn(asset + ".mp4, No such file."); });
mp4 と aacの警告が逆に見えますが、このパスのテストは十分でしょうか。

2017-02-01 04:02 UTC, xnv commented on src/stat.ts
> +		if (sizeResult.aacAudioSize > 0) param.logger.warn("AAC is deprecated. Use MP4 instead.");
MP4(AAC) の表記を徹底していきたいです。この表記がベストかどうかは疑わしいですが、MP4 だけだと何かわからないからです。より丁寧に補足するなら "AAC (.aac) is deprecated. Use MP4(AAC) (.mp4) instead." とかですかね……？

2017-02-01 09:09 UTC, xnv requested changes

2017-02-01 09:09 UTC, xnv commented on src/stat.ts
> +		if (sizeResult.aacAudioSize > 0) param.logger.warn("AAC is deprecated. Use MP4 instead.");
MP4(AAC) の表記を徹底していきたいです。この表記がベストかどうかは疑わしいですが、MP4 だけだと何かわからないからです。より丁寧に補足するなら "AAC (.aac) is deprecated. Use MP4(AAC) (.mp4) instead." とかですかね……？

2017-02-01 09:09 UTC, xnv commented on src/stat.ts
>  		);
これ、  `sizeResult.totalSizeAac())` が 0 の時は非表示でいいんじゃないでしょうか。↓の if 文の中に入れてしまって、正常系では出さない方がいい気もします。

2017-02-01 09:09 UTC, xnv commented on src/stat.ts
> +						() => {if (!param.raw) param.logger.warn(asset + ".aac, No such file."); })
aac がないことは今後正常系になるので、この警告は不要だと思います。(正しく .ogg と .mp4 を用意しているのに、なぜか warn される、というのは意図した状況ではないように思います)　この警告を削除するだけだと他との対称性がない意味が読み取りにくいので、コメントがあるといいかもしれません。(AAC は対応するが deprecated なのでなくても警告しない、というような内容で)

2017-02-01 09:09 UTC, xnv commented on src/stat.ts
> +						() => {if (!param.raw) param.logger.warn(asset + ".mp4, No such file."); });
mp4 と aacの警告が逆に見えますが、このパスのテストは十分でしょうか。

2017-02-01 15:31 UTC, kamakiri01 commented on src/stat.ts
>  		);
AACファイル存在時のみ表示させます。これはテストにも追加します。

2017-02-01 15:32 UTC, kamakiri01 commented on src/stat.ts
> +		if (sizeResult.aacAudioSize > 0) param.logger.warn("AAC is deprecated. Use MP4 instead.");
もう少し情報量を増やして表記を統一します。

2017-02-01 15:33 UTC, kamakiri01 commented on src/stat.ts
> +						() => {if (!param.raw) param.logger.warn(asset + ".aac, No such file."); })
そうですね、正常系で警告は出ないようにします。コメントを残しておきます。

2017-02-01 15:33 UTC, kamakiri01 commented on src/stat.ts
> +						() => {if (!param.raw) param.logger.warn(asset + ".mp4, No such file."); });
テスト追加します。

2017-02-02 05:39 UTC, kamakiri01 commented
新しく追加された ` spec/fixtures/dummyGame4` は 既存 `dummyGame2` のコピーです。
ファイルのエンコード設定でmp4のファイルサイズが最大になるようエンコードしています。

`dummyGame5` も  既存 `dummyGame2` のコピーです。aacファイルを削除した以外は  既存 `dummyGame2` と同内容です。

2017-02-02 05:47 UTC, xnv approved these changes

2017-02-02 06:05 UTC, merged